### ISSUE TITLE
Saving in same folder as source images

### ISSUE THREAD

**Issue by gomiunik** [danice/ICEAutomation#1]
This code is **awesome!!**

Is there a way to make the FlaUI make the ICE store the images in the same location as source images? The problem that occurs with me is that ICE saves images in last used location.

**Comment by danice** [comment]
ICE stores the images in the last location used. So what I do is:
1) process the first group of files manually and selecting the source of the images as destination. 
2) then I move the created stich file to another folder so it does not intefere with the image grouping
3) then I execute the process and all the "stiches" appears in the source folder
