### ISSUE TITLE
Compose command failing

### ISSUE THREAD

**Issue by Sfeeen** [danice/ICEAutomation#11]
Could you provide an example on how to use the compose option.
If I run "ICEAutomation compose pcbscan_count_000.jpg pcbscan_count_001.jpg pcbscan_count_002.jpg"
I get the following:

...
ERROR(S):
  Error setting value to option '': Check if Option or Value attribute values are set properly for the given type.
...

**Comment by danice** [comment]
You are right, it was giving that error with the compose command. I have pushed a fix and now it should work...
