### ISSUE TITLE
It blocks during selecting images

### ISSUE THREAD

**Issue by edoaxyz** [danice/ICEAutomation#2]
When processing more groups of images it blocks at the second/third/fourth group printing some dots because it can't find the button named as "EXPORT". Actually the window seems to have no childs.

**Comment by danice** [comment]
Sorry for the late answer... I was not aware of this issues.

Yes I think I can reproduce this issue. I have created a new version that hopefully fixes that. (but note that the automation technique used is very tricky and sometimes it causes problems...)
