### ISSUE TITLE
Any way to extract the alignment data?

### ISSUE THREAD

**Issue by lvgeng** [danice/ICEAutomation#4]
It works great!

However I might need some flexibility... After call 
stitch.startAlignment()

Is there any way to extract the alignment data? 
I know that ICE would save a project file of alignment data as the project file. Is it possible to extract a file like that with C# code? Or even better, is it possible to get the alignment data by C# code? the public members of StitchEngineWrapper don't have something like that...

**Comment by danice** [comment]
Sorry for the late answer... I was not aware of this issues.

I have created a new version that allows to save each project file. See updated README for details.
