### ISSUE TITLE
Thanks! Could you issue PR against main branch?

### ISSUE THREAD

**Issue by vinyar** [danice/ICEAutomation#5]
Hi, accidentally stumbled on your code via fork (original mentioned here: `https://social.microsoft.com/Forums/en-US/97954687-92e4-466f-a982-5844fcb17bf1/is-there-an-automation-api-available-for-ice?forum=ice` )

Any chance you could issue a PR against the main branch? Seems internet tends to point to that one, even though you made a bunch of improvements.

Thank you!

**Comment by vinyar** [comment]
i am dumb. Sorry

**Comment by vinyar** [comment]
For reference, I was referring to alex232890's changes. You seem to be more active, perhaps you could pull them in?

**Comment by danice** [comment]
thanks for your interest! I don't know if alex232890 branch is ready to be merged. If I receive any PR of course I will try to include it.
