### ISSUE TITLE
Build application

### ISSUE THREAD

**Issue by MartinStokelj** [danice/ICEAutomation#8]
I have problem building the project.

**The project has to be compiled using Visual Studio 2017** I am using 2017.

The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.

I have installed .NET Core 3.1.  But I don't see it in VS2017, on web it says that only VS2019 supports 3.1.
So I have selected 2.1 in project, but I get next error in line.

`
                .WithParsed<ComposeOptions>(options => Compose(options))
`

A local or parameter named 'options' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

**Comment by danice** [comment]
Hello,
Now the project has moved to netcoreapp3.1. I recommend you to use VS Code but you only need .net core 3.1 SDK to build it. Follow this:
1) install [dot.net core 3.1 SDK](https://dotnet.microsoft.com/download/dotnet-core/3.1)
2) open a cmd and move to your projects folder and execute:
```
> git clone https://github.com/danice/ICEAutomation.git
> cd ICEAutomation
> dotnet build
```
You will found the compiled files in <projects>\ICEAutomation\src\bin\Debug\netcoreapp3.1
Then adjust the ICEAutomation.bat to point to this folder and copy it to c:\Windows folder. Then it will be in you path and you can call it in cmd from any folder.

**Comment by MartinStokelj** [comment]
Thanx for info, it works.
